added user endpoints for entry, entries, review, reviews, and account
PeerRequest/api_spec pull request #13
Opened 2022-12-09 15:10 UTC by veropossumus

irgendwas stimmt mit den Referenzen nicht, ich konnte es aber bisher nicht lösen.

2022-12-09 16:29 UTC, bits0rcerer requested changes
Good start. :+1:

2022-12-09 16:29 UTC, bits0rcerer commented on src/openapi.yaml
> +  /{user_id}/account:
```suggestion
  /users/{user_id}:
```
`GET` on `/users/{user_id}` would be a perfect fit here

2022-12-09 16:29 UTC, bits0rcerer commented on src/parameters/path/user_id.yaml
> +description: The id of the signed-in user
```suggestion
description: The id of a user
```
The user specified might not be the one doing the request.

2022-12-09 16:29 UTC, bits0rcerer commented on src/paths/user/account.yaml
> +  description: "Show the account details of the signed-in user"
```suggestion
  description: "Show the account details of a user"
```
The user specified might not be the one doing the request.

2022-12-09 16:29 UTC, bits0rcerer commented on src/paths/user/account.yaml
> +      description: "Account details of the signed-in user"
```suggestion
      description: "Account details of a user"
```
The user specified might not be the one doing the request.

2022-12-09 16:29 UTC, bits0rcerer commented on src/openapi.yaml
> +  # user endpoints
Please put all endpoints concerning users under `/users`.

Lets say we make an API request like `https://peerreq.com/categories/...`
Is this a request about categories or a user with the `id` _categories_?

You normally do not want a parameter at the path root.

2022-12-09 16:29 UTC, bits0rcerer commented on src/paths/user/entries.yaml
> +  description: "Returns all entries of the signed-in user"
same as above

2022-12-09 16:29 UTC, bits0rcerer commented on src/paths/user/entry.yaml
> +  description: "Returns one entry created by the signed-in user"
same as above

2022-12-09 16:29 UTC, bits0rcerer commented on src/paths/user/review.yaml
> +  description: "Returns one review created by the signed-in user"
same as above

2022-12-09 16:29 UTC, bits0rcerer commented on src/openapi.yaml
> +  # user endpoints
Please include the path parameters in the directory structure as well.

2022-12-09 16:29 UTC, bits0rcerer commented on src/paths/user/reviews.yaml
> +  description: "Returns all reviews of the signed-in user"
same as above

2022-12-09 18:50 UTC, bits0rcerer commented on src/openapi.yaml
> +    $ref: "./parameters/paths/user/entries.yaml"
```suggestion
    $ref: "./paths/user/user_id/entries.yaml"
```

2022-12-09 18:52 UTC, bits0rcerer commented on src/openapi.yaml
> +    $ref: "./parameters/paths/user/entry.yaml"
```suggestion
    $ref: "./paths/users/user_id/entries/entry_id/entry.yaml"
```

2022-12-09 18:52 UTC, bits0rcerer commented on src/openapi.yaml
> +    $ref: "./parameters/paths/user/reviews.yaml"
```suggestion
    $ref: "./paths/users/user_id/reviews.yaml"
```

2022-12-09 18:54 UTC, bits0rcerer commented on src/openapi.yaml
> +    $ref: "./parameters/paths/user/review.yaml"
```suggestion
    $ref: "./paths/users/user_id/reviews/review_id/review.yaml"
```

2022-12-09 18:54 UTC, bits0rcerer commented on src/openapi.yaml
> +     $ref: "./parameters/paths/user/account.yaml"
```suggestion
     $ref: "./paths/users/user_id/user.yaml"
```

2022-12-10 15:39 UTC, bits0rcerer requested changes

2022-12-10 15:39 UTC, bits0rcerer commented on src/openapi.yaml
> +  /users/{user_id}/reviews:
When do you think this request is being called?

I currently do not see a scenario where a user might request all reviews of a specific user. As far as I know this is confidential information therefor a user should only be able to find reviews in the context of an entry, they are associated with.

Please correct me if I am missing something.

2022-12-10 15:39 UTC, bits0rcerer commented on src/openapi.yaml
> +  /users/{user_id}/reviews/{review_id}:
Same as above.

2022-12-10 15:39 UTC, bits0rcerer commented on src/parameters/path/user_id
> +name: user_id
Is this file supposed to be here?

2022-12-10 15:39 UTC, bits0rcerer commented on src/openapi.yaml
> +    $ref: "./paths/users/user_id/account.yaml"
```suggestion
    $ref: "./paths/users/user_id/user.yaml"
```
Please rename this file for consistency.

2022-12-10 15:39 UTC, bits0rcerer commented on src/paths/users/user_id/account.yaml
> +            type: array
Since this response only contains one user this does not have to be an array.

2022-12-10 15:39 UTC, bits0rcerer commented on src/openapi.yaml
> +  /users/{user_id}/entries/{entry_id}:
I gave this some thought and came to the conclusion that this endpoint might be redundant. Because when you request an entry (implying you know the `entry_id`) you can as well just use `/entries/{entry_id}`.

Please correct me when you think this endpoint provides value I am currently issing.

2022-12-10 15:39 UTC, bits0rcerer commented on src/paths/users/user_id/entries/entry_id/entry.yaml
> +            type: array
same as above

2022-12-10 15:41 UTC, bits0rcerer commented
I think it would be highly beneficial when we could have an endpoint like `/users/self` to allow users to obtain information about themselves.

2022-12-10 16:43 UTC, veropossumus commented on src/paths/users/user_id/account.yaml
> +            type: array
What should it be instead? The goal is not to simply return the user id but all account details.

2022-12-10 17:13 UTC, bits0rcerer commented on src/paths/users/user_id/account.yaml
> +            type: array
Just a simple object, not an array.

```yaml
  responses:
    200:
      description: "Account details of a user"
      content:
        application/json:
          schema:
            $ref: "../../../schemas/user.yaml"
```

2022-12-10 17:35 UTC, bits0rcerer approved these changes

2022-12-10 17:35 UTC, merged